### ISSUE TITLE
Stderr from streamgraph cluttering stderr stream from actual process

### ISSUE THREAD

**Issue by apregier** [tabbott/streamgraph#1]
I'm noticing in this latest version that the stderr output from the process management stuff is getting inserted into the stderr of the actual process that we care about.  I forget if this is a known issue/intended?  For example, in your example xml, the flagstat.log and calmd.log files end up with a bunch of lines like: 
I0317 10:49:37.879420  2291 FdMapping.cpp:75] final dup2(13, 2) -> 2
I0317 10:49:37.879448  2291 FdMapping.cpp:84] closed unused fd 3

**Comment by tabbott** [comment]
Uh, I thought I fixed that. Maybe I didn't push, just a sec ...

**Comment by tabbott** [comment]
Didn't even commit it! Doing so now...

**Comment by tabbott** [comment]
Let me know if you are satisfied with commit d294de316c1650f4825851341d9c5a3d1ae0105b. I also hadn't pushed the .dot output capability.

**Comment by apregier** [comment]
Yes, this seems to have fixed it, thanks!
